services:
  mysql:
    image: mysql:8.0
    networks:
      - web
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'root'
      MAYSQL_TZ: ${TZ}
    volumes:
      - mysql_data:/var/lib/mysql
      - "./mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
      #- "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    command: 
      - --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    networks:
      - web
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  traefik:
    image: traefik:2.11.2
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=web"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=network_public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - --certificatesresolvers.letsencryptresolver.acme.email=${LETS_ENCRYPT_EMAIL}
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--log.level=DEBUG"
      - "--log.format=common"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access-log"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "vol_certificates:/etc/traefik/letsencrypt"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - web
    labels:
     - "traefik.enable=true"
     - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
     - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
     - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
     - "traefik.http.routers.http-catchall.entrypoints=web"
     - "traefik.http.routers.http-catchall.middlewares=redirect-https@docker"
     - "traefik.http.routers.http-catchall.priority=1"

volumes:
  mysql_data:
  vol_certificates:
    external: true
    name: volume_swarm_certificates
  evolution_redis:

networks:
  web:
    external: true